name: pythia_generator
description: Pulling the data from the cloud to make supporting data for Pythia
publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'
  
dependencies:
  csv: ^6.0.0
  fhir: ^0.12.0
  gsheets: ^0.5.0
  json_annotation: ^4.8.1
  pythia: 
    path: ../pythia
  riverpod_annotation: ^2.3.4

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1