name: pythia
description: Immunization Forecasting Engine for use with Dart and FHIR
version: 0.0.1
homepage: https://github.com/Dokotela/pythia/pythia

environment:
  sdk: '>=2.19.0 <3.0.0'
  
dependencies:
  collection: ^1.15.0
  date_utils: ^0.2.0
  fhir: ^0.9.4
  freezed_annotation: ^2.2.0

dev_dependencies:
  test: ^1.23.1
  build_runner: ^2.1.7
  freezed: ^2.3.2